#!/bin/bash

rm -r $3/`head -n 1 hierarchy/$2`
rm -r $3/`head -n 1 hierarchy/$2`.md
rm -r `head -n 1 hierarchy/$2`
rm -r `head -n 1 hierarchy/$2`.md

zipinfo -2 $1 > FilesPath

./cpp/ChangePath FilesPath hierarchy/$2

rm FilesPath

cat hierarchy/$2 | while read i;
do
    echo $i
done

cat hierarchy/$2 | while read i;
do
    echo $i
    mkdir "$i"
done

cat CorrectFilesPath | while read i;
do
    read j

    unzip -p -c $1 "$i" > "$j"
done;

./cpp/TexCorrector change_command `head -n 1 hierarchy/$2`.md.e CorrectFilesPath
rm `head -n 1 hierarchy/$2`.md.e

cat hierarchy/$2 | while read i;
do
    ls $i/*.md.e | while read j;
    do
        ./cpp/TexCorrector change_command $j CorrectFilesPath
        rm $j
    done;
done

rm CorrectFilesPath

mkdir $3
mv `head -n 1 hierarchy/$2`.md ./`head -n 1 hierarchy/$2` $3